### ISSUE TITLE
Restoring auto rotate

### ISSUE THREAD

**Issue by fennectech** [kyaulabs/win11tweak#2]
how would you restore autorotate doing essential tweaks removes auto rotation and restoring essential fixes it.   what part of the essential tweaks disabled it

**Comment by fennectech** [comment]
looks like sensors are disabled along with other location stuff in policies   i turned them back on

**Comment by kyau** [comment]
Correct, this was originally designed for workstations. If you wanted to use it with tablets and/or laptops I would also look at the power management changes as well. (Assuming that is the type of device you are referring to when bringing up auto rotation.)

**Comment by fennectech** [comment]
Aight!    You should add a “portable computer” option that leaves stuff like this enabled.    The machine i have is a dell venue 10 pro 5056 with an atom x5 with 4gb of ram.  So resources are extra important there!

**Comment by kyau** [comment]
As I do not have a system to test this on myself (with auto-rotate), would you mind forwarding me the setting that you reenabled which fixed this on your end, I will add an option to the user config.

**Comment by kyau** [comment]
To clarify was auto rotate being disabled completely? or is it merely locked (I think this is the new Windows 11 default).

This may or may not be relevant: https://www.elevenforum.com/t/turn-on-or-off-screen-rotation-lock-in-windows-11.2603/

**Comment by fennectech** [comment]
It can be fixed by re enabling some of the tracking features.   Spesificly the censors.     What this does prevents rotation lock from being used
