### ISSUE TITLE
How to add programs to choco

### ISSUE THREAD

**Issue by podaen** [kyaulabs/win11tweak#22]
Hi,

Can I just add those to the user_settings.ps1 $script:ChocoPkgs or is there an other way? And what is preferred installer is preferred? because sometimes I see multiple versions... "<NAME>.install" or just <NAME>? Is it possible to add parameters too?

**Comment by kyau** [comment]
Yes you are correct, the array `$script:ChocoPkgs` holds the names of the packages that are installed automatically by `chocolatey` on installation.

Obviously, other applications (say something not provided by `chocolatey`) that you wish to install you can manipulate the script manually in any way you want to install other stuff. You can see ways of doing this in `cleanup.ps1` installing `MSYS2` for example.

**Comment by podaen** [comment]
Cool, thanks! Most of the application I could find in it. There are a few, but I prefer to install them manually. I see I can download the apps. That's useful!
