### ISSUE TITLE
Missing apps in Win11 start

### ISSUE THREAD

**Issue by podaen** [kyaulabs/win11tweak#23]
Hi,

Some apps are missing in to win11 start, also win search can't find it. The Everything app can find it! 

For example pdfsumatra is not in to the app list, but why is that? Because it is a only a link, so the uninstall on right click (shell) is missing??

![Everything_ZUoiD5lhLa](https://github.com/kyaulabs/win11tweak/assets/63886347/2b887722-e613-4726-aaf5-9126eb74feab)

MSI tomahawk DDR5 Z790
Intel 13600K
OS build 22621 GB/UK

**Comment by kyau** [comment]
I believe it is a portable version of SumatraPDF that is installed, that is why there is no uninstaller included. However it was installed via `chocolatey`, therefore `chocolatey` can easily remove it. Feel free to use Chocolatey GUI or the command line with `choco.exe` to get rid of it.

**Comment by kyau** [comment]
One of the main points of using a package manager such as `chocolatey` is that you can use it to auto-update all the applications without the need to visit 100 different websites to check for new versions. And while a lot of modern applications have auto updates built-in often this will fail, leaving you with an stale version.

To utilize this the full capability it is recommended to do all installing updating and uninstalling through the package manager. While you can obviously uninstall any application the normal way, if it was installed with `chocolatey` and yet removed with `Installed Apps` there will be a stale installed entry to remove in the local internal `chocolatey` database.

**Comment by podaen** [comment]
Most importendly it is missing in "all apps" in the "start menu". 

![xfJx49apHv](https://github.com/kyaulabs/win11tweak/assets/63886347/3ea37e81-47a6-4ae8-981e-a164960128ef)

There is an other installer then ID "sumatrapdf" , "sumatrapdf.install". Don't know what that means, 
![ChocolateyGui_qcE0Mac8ss](https://github.com/kyaulabs/win11tweak/assets/63886347/ea70a888-8f59-4aea-8a95-e8479a26918e)

but when I look at the official webpage it doesn't support win11 yet. Maybe that's why...
https://www.sumatrapdfreader.org/download-free-pdf-viewer

I didn't install 'ClassicShell' yet, maybe that brings back the app in to the 'start menu'??

**Comment by podaen** [comment]
Sorry, "sumatrapdf.portable" is also in choco. Don't know why it wasn't showed. It is an open sourced. That's something I like!

**Comment by podaen** [comment]
Got it fixed. I did the SFC /scannow in cmd and reinstalled sumatrapdf.

```
> Microsoft Windows [Version 10.0.22621.1702]
> (c) Microsoft Corporation. All rights reserved.
> 
> C:\Windows\System32>SFC /scannow
> 
> Beginning system scan.  This process will take some time.
> 
> Beginning verification phase of system scan.
> Verification 100% complete.
> 
> Windows Resource Protection found corrupt files and successfully repaired them.
> For online repairs, details are included in the CBS log file located at
> windir\Logs\CBS\CBS.log. For example C:\Windows\Logs\CBS\CBS.log. For offline
> repairs, details are included in the log file provided by the /OFFLOGFILE flag.
```

I checked the log of the SFC that There was an issue with the installation. 

> 2023-08-27 00:51:34, Info                  DEPLOY [Pnp] Corrupt file: C:\Windows\System32\drivers\bthmodem.sys
> 2023-08-27 00:51:34, Info                  DEPLOY [Pnp] Repaired file: C:\Windows\System32\drivers\bthmodem.sys

When I look at the driver it seems that is a Bluetooth modem driver. Don't understand this could be an issue installing packages. Maybe just a reinstall Sumatra like you told me could have solved it.

This network issue could be related to MSI board, because it comes with an driver updater in UEFI that takes drivers out of the cloud and since there is no network during installation...  But the issue is repaired now. Maybe only a "Network Reset" in "Windows Setting" would have helped. I don't know...

After I reinstalled Sumatra the app could be find in to start.
