### ISSUE TITLE
How to run a ps1 with admin rights

### ISSUE THREAD

**Issue by podaen** [kyaulabs/win11tweak#24]
When I follow the script it start with main.cmd-> default.cmd -> default.ps1

I tried to check to do this

Create a shortcut to your Powershell script on your desktop
Right-click the shortcut and click Properties
Click the Shortcut tab
Click Advanced
Select Run as Administrator

but it isn't there...

Is this enough to run ps1 files with privileges?

https://github.com/kyaulabs/win11tweak/blob/master/README_media/Windows_08.png

Now I ask myself, the next time it opens after reboot windows. Does it still have the admin rights?

**Comment by podaen** [comment]
The first is runed as admin, the only problem I have... Is that when try some new code I use the windows Powerscript SE that doesn't come along with admin when selecting one from here C:\users\<USER>\Desktop\win11tweak\modules. Maybe I have to open it by the terminal and navigate to it. Stil don't know how can open a tab from the or is VS a much better chois?

I would like to ad my personal code to my own PS1. Is the only way to ad some reference in one of the PS1 to my mod?

**Comment by kyau** [comment]
win11tweak flow:

`main.cmd` (run manually as admin) >> `Modules/defaults.cmd` (inherits admin) >> `Modules/defaults.ps1` (inherits admin)

From here you should notice that `defaults.ps1` sources `_funcs.ps1` this file contains functionality that is shared by all scripts, such as the visual output of the sections and items during installation.

![ImageGlass_Xnp9siQIc4](https://github.com/kyaulabs/win11tweak/assets/470450/71d7b27a-d668-48ae-a18d-eeac2ae9521c)

```powershell
Show-Section -Section "Apps" -Desc "Remove 3rd Party Bloat"
```

You should also see at the bottom of said file how it is including all of the other files inside of the `Modules` folder. The tricky part is only if you want to run something as a normal user, this is done via my `Show-RunAsUser` function in `_funcs.ps1` but is basically a hack.

**Comment by podaen** [comment]
Yes indeed, it's a hack of me. I have mad a start menu config for win11. But I can't get it imported in to the windows image without running the whole win11tweak script. Just want to test a part of it...

And I don't see a way using the Windows Powershell ISE to run it as admin with the missing tab on file properties.

**Comment by podaen** [comment]
About those section... Can I disable them individually?

**Comment by podaen** [comment]
Ooops, found a way to open it with admin rights. First open the app with admin rights and then open the file.
