### ISSUE TITLE
Question about username

### ISSUE THREAD

**Issue by podaen** [kyaulabs/win11tweak#25]
I have a question about the user name from git filled in to Settings.PS1. Does it need to be the username of the computer or is it the username of Github... Or are the best the same?

**Comment by kyau** [comment]
```powershell
$script:UserName = ${Env:UserName}.ToLower()
```

This means it will use the current logged in username in Windows as the Git username.

Edit: in lowercase.

**Comment by podaen** [comment]
Does that name of Git mater to push a repo in to the online Github account?

**Comment by kyau** [comment]
Pulled directly from the manual page: `git-config(1)`

```text
user.name, user.email, author.name, author.email, committer.name,
 committer.email
	The user.name and user.email variables determine what ends up
	in the author and committer field of commit objects. If you
	need the author or committer to be different, the
	author.name, author.email, committer.name or committer.email
	variables can be set. Also, all of these can be overridden by
	the GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL, GIT_COMMITTER_NAME,
	GIT_COMMITTER_EMAIL and EMAIL environment variables.
```

Those are setup to set the `user.name` and `user.email` fields, so that you have sane defaults for pushing with `git`.

You can see the `.gitconfig` file being made here: [`cleanup.ps1:206`](https://github.com/kyaulabs/win11tweak/blob/master/Modules/cleanup.ps1#L206)

**Comment by podaen** [comment]
I missed it! thanks, now I understand.

**Comment by podaen** [comment]
It's new to me. I started with an extension, then used the github application an now want to use it like a plugin.

For people that are also new to this. Here some more info about this topic

https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git
